# Data source for the "arb" svn merge tool (see http://github.com/sminnee/arborist).
# Keeps track of all opensource branches of submodules 
# that could be merged back to the current submodule paths.
trunk:
  .: /open/phpinstaller/trunk
  sapphire: /open/modules/sapphire/trunk
  cms: /open/modules/cms/trunk

sscom:
 sapphire: /modules/sapphire/branches/2.4-sscom
 cms: /modules/cms/branches/2.4-sscom

