# Data source for the "arb" svn merge tool (see http://github.com/sminnee/arborist).
# Keeps track of all opensource branches of submodules 
# that could be merged back to the current submodule paths.
2.3:
  sapphire: /open/modules/sapphire/branches/2.3
  cms: /open/modules/cms/branches/2.3
  jsparty: /open/modules/jsparty/branches/2.3